CREATE TABLE [dbo].[Branch] (
    [BranchID]             INT            NOT NULL,
    [Branch]               NVARCHAR (50)  NOT NULL,
    [Region]               NVARCHAR (50)  NOT NULL,
    [StreetAddress]        NVARCHAR (MAX) NULL,
    [City]                 NVARCHAR (50)  NOT NULL,
    [State]                NVARCHAR (50)  NULL,
    [Zip]                  NVARCHAR (50)  NULL,
    [Phone]                NVARCHAR (50)  NULL,
    [Fax]                  NVARCHAR (50)  NULL,
    [BranchNumber]         INT            NULL,
    [RemitToStreetAddress] NVARCHAR (MAX) NULL,
    [RemitToCity]          NVARCHAR (50)  NULL,
    [RemitToState]         NVARCHAR (20)  NULL,
    [RemitToZip]           NVARCHAR (20)  NULL,
    [BranchSignatoryFName] NVARCHAR (50)  NULL,
    [BranchSignatoryLName] NVARCHAR (50)  NULL,
    [BranchSignatoryTitle] NVARCHAR (50)  NULL,
    [BranchSignatoryEmail] NVARCHAR (50)  NULL,
    [InvoicePhoneNum]      NVARCHAR (20)  NULL,
    [RepairCoordEmail]     NVARCHAR (MAX) NULL,
    [ModContractEmail]     NVARCHAR (MAX) NULL,
    [ModInvoicePhoneNum]   NVARCHAR (20)  NULL,
    [StartTime]            NVARCHAR (50)  NULL,
    [EndTime]              NVARCHAR (50)  NULL,
    [CreatedBy]            NVARCHAR (50)  NULL,
    [CreatedOn]            NVARCHAR (50)  NULL,
    [ModifiedBy]           NVARCHAR (50)  NULL,
    [ModifiedOn]           DATETIME       NULL,
    [IsDeleted]            BIT            NULL,
    PRIMARY KEY CLUSTERED ([BranchID] ASC)
);

