//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecMemoService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://thyssenkrupp.com/ESR/ET/MFT/PLM/PLM", ConfigurationName="SpecMemoService.SpecMemoOBOM_CreateUpdate_Out")]
    public interface SpecMemoOBOM_CreateUpdate_Out
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://sap.com/xi/WebService/soap1.1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task SpecMemoOBOM_CreateUpdate_OutAsync(SpecMemoService.SpecMemoOBOM_CreateUpdate_Out1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thyssenkrupp.com/ESR/ET/COMMON/FOUNDATION/PP")]
    public partial class SpecMemoShipOBOM
    {
        
        private BusinessDocumentMessageHeader messageHeaderField;
        
        private SpecMemoShipOBOMElevator[] elevatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public BusinessDocumentMessageHeader MessageHeader
        {
            get
            {
                return this.messageHeaderField;
            }
            set
            {
                this.messageHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Elevator", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public SpecMemoShipOBOMElevator[] Elevator
        {
            get
            {
                return this.elevatorField;
            }
            set
            {
                this.elevatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thyssenkrupp.com/ESR/CORE/FOUNDATION/CM")]
    public partial class BusinessDocumentMessageHeader
    {
        
        private string uUIDField;
        
        private System.DateTime creationDateTimeField;
        
        private string senderBusinessSystemIDField;
        
        private string recipientBusinessSystemIDField;
        
        private string trackingIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime CreationDateTime
        {
            get
            {
                return this.creationDateTimeField;
            }
            set
            {
                this.creationDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=2)]
        public string SenderBusinessSystemID
        {
            get
            {
                return this.senderBusinessSystemIDField;
            }
            set
            {
                this.senderBusinessSystemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=3)]
        public string RecipientBusinessSystemID
        {
            get
            {
                return this.recipientBusinessSystemIDField;
            }
            set
            {
                this.recipientBusinessSystemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=4)]
        public string TrackingID
        {
            get
            {
                return this.trackingIDField;
            }
            set
            {
                this.trackingIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://thyssenkrupp.com/ESR/ET/COMMON/FOUNDATION/PP")]
    public partial class SpecMemoShipOBOMElevator
    {
        
        private string uniqueEquipmentIDField;
        
        private string changeNumberField;
        
        private string sourceSystemField;
        
        private string mfgtProjectIDField;
        
        private string mfgtWBSNOField;
        
        private string plantField;
        
        private string senderUserField;
        
        private string sendingTypeField;
        
        private SpecMemoShipOBOMElevatorSpecMemo specMemoField;
        
        private SpecMemoShipOBOMElevatorItem[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string UniqueEquipmentID
        {
            get
            {
                return this.uniqueEquipmentIDField;
            }
            set
            {
                this.uniqueEquipmentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string ChangeNumber
        {
            get
            {
                return this.changeNumberField;
            }
            set
            {
                this.changeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string SourceSystem
        {
            get
            {
                return this.sourceSystemField;
            }
            set
            {
                this.sourceSystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=3)]
        public string MfgtProjectID
        {
            get
            {
                return this.mfgtProjectIDField;
            }
            set
            {
                this.mfgtProjectIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=4)]
        public string MfgtWBSNO
        {
            get
            {
                return this.mfgtWBSNOField;
            }
            set
            {
                this.mfgtWBSNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=5)]
        public string Plant
        {
            get
            {
                return this.plantField;
            }
            set
            {
                this.plantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string SenderUser
        {
            get
            {
                return this.senderUserField;
            }
            set
            {
                this.senderUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=7)]
        public string SendingType
        {
            get
            {
                return this.sendingTypeField;
            }
            set
            {
                this.sendingTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public SpecMemoShipOBOMElevatorSpecMemo SpecMemo
        {
            get
            {
                return this.specMemoField;
            }
            set
            {
                this.specMemoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public SpecMemoShipOBOMElevatorItem[] Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://thyssenkrupp.com/ESR/ET/COMMON/FOUNDATION/PP")]
    public partial class SpecMemoShipOBOMElevatorSpecMemo
    {
        
        private string specMemoVersionField;
        
        private SpecMemoShipOBOMElevatorSpecMemoCharacteristics[] characteristicsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string SpecMemoVersion
        {
            get
            {
                return this.specMemoVersionField;
            }
            set
            {
                this.specMemoVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Characteristics", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public SpecMemoShipOBOMElevatorSpecMemoCharacteristics[] Characteristics
        {
            get
            {
                return this.characteristicsField;
            }
            set
            {
                this.characteristicsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://thyssenkrupp.com/ESR/ET/COMMON/FOUNDATION/PP")]
    public partial class SpecMemoShipOBOMElevatorSpecMemoCharacteristics
    {
        
        private string classNameField;
        
        private string characNameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ClassName
        {
            get
            {
                return this.classNameField;
            }
            set
            {
                this.classNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CharacName
        {
            get
            {
                return this.characNameField;
            }
            set
            {
                this.characNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://thyssenkrupp.com/ESR/ET/COMMON/FOUNDATION/PP")]
    public partial class SpecMemoShipOBOMElevatorItem
    {
        
        private string componentItemField;
        
        private string componentMaterialNoField;
        
        private decimal desiredQuantityField;
        
        private string uOMField;
        
        private string cTOorETOField;
        
        private string modelVersionField;
        
        private string revisionField;
        
        private SpecMemoShipOBOMElevatorItemCharacteristic[] characteristicField;
        
        private SpecMemoShipOBOMElevatorItemBOMParent[] bOMParentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ComponentItem
        {
            get
            {
                return this.componentItemField;
            }
            set
            {
                this.componentItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string ComponentMaterialNo
        {
            get
            {
                return this.componentMaterialNoField;
            }
            set
            {
                this.componentMaterialNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal DesiredQuantity
        {
            get
            {
                return this.desiredQuantityField;
            }
            set
            {
                this.desiredQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=3)]
        public string UOM
        {
            get
            {
                return this.uOMField;
            }
            set
            {
                this.uOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CTOorETO
        {
            get
            {
                return this.cTOorETOField;
            }
            set
            {
                this.cTOorETOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=5)]
        public string ModelVersion
        {
            get
            {
                return this.modelVersionField;
            }
            set
            {
                this.modelVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Revision
        {
            get
            {
                return this.revisionField;
            }
            set
            {
                this.revisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Characteristic", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public SpecMemoShipOBOMElevatorItemCharacteristic[] Characteristic
        {
            get
            {
                return this.characteristicField;
            }
            set
            {
                this.characteristicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BOMParent", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public SpecMemoShipOBOMElevatorItemBOMParent[] BOMParent
        {
            get
            {
                return this.bOMParentField;
            }
            set
            {
                this.bOMParentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://thyssenkrupp.com/ESR/ET/COMMON/FOUNDATION/PP")]
    public partial class SpecMemoShipOBOMElevatorItemCharacteristic
    {
        
        private string classNameField;
        
        private string characNameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ClassName
        {
            get
            {
                return this.classNameField;
            }
            set
            {
                this.classNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CharacName
        {
            get
            {
                return this.characNameField;
            }
            set
            {
                this.characNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://thyssenkrupp.com/ESR/ET/COMMON/FOUNDATION/PP")]
    public partial class SpecMemoShipOBOMElevatorItemBOMParent
    {
        
        private string materialInternalIDField;
        
        private SpecMemoShipOBOMElevatorItemBOMParentBOMChild[] bOMChildField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string MaterialInternalID
        {
            get
            {
                return this.materialInternalIDField;
            }
            set
            {
                this.materialInternalIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BOMChild", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public SpecMemoShipOBOMElevatorItemBOMParentBOMChild[] BOMChild
        {
            get
            {
                return this.bOMChildField;
            }
            set
            {
                this.bOMChildField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://thyssenkrupp.com/ESR/ET/COMMON/FOUNDATION/PP")]
    public partial class SpecMemoShipOBOMElevatorItemBOMParentBOMChild
    {
        
        private string itemNumberField;
        
        private string materialInternalIDField;
        
        private string itemCategoryField;
        
        private string uOMField;
        
        private decimal desiredQuantityField;
        
        private string itemTextLine1Field;
        
        private decimal componentScrapPercentField;
        
        private bool componentScrapPercentFieldSpecified;
        
        private string revisionField;
        
        private SpecMemoShipOBOMElevatorItemBOMParentBOMChildCharacteristic[] characteristicField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ItemNumber
        {
            get
            {
                return this.itemNumberField;
            }
            set
            {
                this.itemNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string MaterialInternalID
        {
            get
            {
                return this.materialInternalIDField;
            }
            set
            {
                this.materialInternalIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=2)]
        public string ItemCategory
        {
            get
            {
                return this.itemCategoryField;
            }
            set
            {
                this.itemCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=3)]
        public string UOM
        {
            get
            {
                return this.uOMField;
            }
            set
            {
                this.uOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal DesiredQuantity
        {
            get
            {
                return this.desiredQuantityField;
            }
            set
            {
                this.desiredQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ItemTextLine1
        {
            get
            {
                return this.itemTextLine1Field;
            }
            set
            {
                this.itemTextLine1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal ComponentScrapPercent
        {
            get
            {
                return this.componentScrapPercentField;
            }
            set
            {
                this.componentScrapPercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ComponentScrapPercentSpecified
        {
            get
            {
                return this.componentScrapPercentFieldSpecified;
            }
            set
            {
                this.componentScrapPercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Revision
        {
            get
            {
                return this.revisionField;
            }
            set
            {
                this.revisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Characteristic", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public SpecMemoShipOBOMElevatorItemBOMParentBOMChildCharacteristic[] Characteristic
        {
            get
            {
                return this.characteristicField;
            }
            set
            {
                this.characteristicField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://thyssenkrupp.com/ESR/ET/COMMON/FOUNDATION/PP")]
    public partial class SpecMemoShipOBOMElevatorItemBOMParentBOMChildCharacteristic
    {
        
        private string classNameField;
        
        private string characNameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ClassName
        {
            get
            {
                return this.classNameField;
            }
            set
            {
                this.classNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CharacName
        {
            get
            {
                return this.characNameField;
            }
            set
            {
                this.characNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SpecMemoOBOM_CreateUpdate_Out1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Order=0)]
        public SpecMemoService.SpecMemoShipOBOM SpecMemoOBOM_CreateUpdate_Request;
        
        public SpecMemoOBOM_CreateUpdate_Out1()
        {
        }
        
        public SpecMemoOBOM_CreateUpdate_Out1(SpecMemoService.SpecMemoShipOBOM SpecMemoOBOM_CreateUpdate_Request)
        {
            this.SpecMemoOBOM_CreateUpdate_Request = SpecMemoOBOM_CreateUpdate_Request;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface SpecMemoOBOM_CreateUpdate_OutChannel : SpecMemoService.SpecMemoOBOM_CreateUpdate_Out, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class SpecMemoOBOM_CreateUpdate_OutClient : System.ServiceModel.ClientBase<SpecMemoService.SpecMemoOBOM_CreateUpdate_Out>, SpecMemoService.SpecMemoOBOM_CreateUpdate_Out
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SpecMemoOBOM_CreateUpdate_OutClient(EndpointConfiguration endpointConfiguration) : 
                base(SpecMemoOBOM_CreateUpdate_OutClient.GetBindingForEndpoint(endpointConfiguration), SpecMemoOBOM_CreateUpdate_OutClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SpecMemoOBOM_CreateUpdate_OutClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SpecMemoOBOM_CreateUpdate_OutClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SpecMemoOBOM_CreateUpdate_OutClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SpecMemoOBOM_CreateUpdate_OutClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SpecMemoOBOM_CreateUpdate_OutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task SpecMemoService.SpecMemoOBOM_CreateUpdate_Out.SpecMemoOBOM_CreateUpdate_OutAsync(SpecMemoService.SpecMemoOBOM_CreateUpdate_Out1 request)
        {
            return base.Channel.SpecMemoOBOM_CreateUpdate_OutAsync(request);
        }
        
        public System.Threading.Tasks.Task SpecMemoOBOM_CreateUpdate_OutAsync(SpecMemoService.SpecMemoShipOBOM SpecMemoOBOM_CreateUpdate_Request)
        {
            SpecMemoService.SpecMemoOBOM_CreateUpdate_Out1 inValue = new SpecMemoService.SpecMemoOBOM_CreateUpdate_Out1();
            inValue.SpecMemoOBOM_CreateUpdate_Request = SpecMemoOBOM_CreateUpdate_Request;
            return ((SpecMemoService.SpecMemoOBOM_CreateUpdate_Out)(this)).SpecMemoOBOM_CreateUpdate_OutAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                return new System.ServiceModel.EndpointAddress(@"http://av000qpe.erp.hp.thyssenkrupp.com:54300/XISOAPAdapter/MessageServlet?senderParty=&senderService=THIRD_ET_PLM_Q&receiverParty=&receiverService=&interface=SpecMemoOBOM_CreateUpdate_Out&interfaceNamespace=http%3A%2F%2Fthyssenkrupp.com%2FESR%2FET%2FMFT%2FPLM%2FPLM");
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                return new System.ServiceModel.EndpointAddress(@"https://av000qpe.erp.hp.thyssenkrupp.com:54301/XISOAPAdapter/MessageServlet?senderParty=&senderService=THIRD_ET_PLM_Q&receiverParty=&receiverService=&interface=SpecMemoOBOM_CreateUpdate_Out&interfaceNamespace=http%3A%2F%2Fthyssenkrupp.com%2FESR%2FET%2FMFT%2FPLM%2FPLM");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HTTP_Port,
            
            HTTPS_Port,
        }
    }
}
